name: 'Open API Diff'
description: 'Compares one or more Open API Specification files'
inputs:
  baseFiles:
    description: 'pattern of base openapi files'
    required: true
  headFiles:
    description: 'pattern of head openapi files'
    required: true
  github_token:
    description: 'token to create issue with'
    required: true
  repo:
    description: The owner and repository name. e.g.) Codertocat/Hello-World
    required: false
    default: ${{ github.repository }}
runs:
  using: 'node16'
  main: 'dist/index.js'
